import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./nav/Navbar";
import { Toaster } from "@/components/ui/toaster";
import TanstackProvider from "@/components/TanstackProvider";
import NextTopLoader from 'nextjs-toploader';

export const metadata: Metadata = {
  title: "vet-client",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={{ minWidth: "98vw", maxWidth: "100%", height: "90vh" }}>
        <TanstackProvider>
          <Navbar />
          <main className="p-0" style={{ minWidth: "98%", maxHeight: "90vh" }}>
            <NextTopLoader color="#4edd22" height={5} />
            {children}
          </main>
          <Toaster />
        </TanstackProvider>
      </body>
    </html>
  );
}
