import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./nav/Navbar";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "vet-client",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={{minWidth:"100vw", height: '90vh'}}>
        <Navbar/>
        <main className="p-10" style={{minWidth:"100%", minHeight: '90vh'}}>
          {children}
        </main>
        <Toaster />
      </body>
    </html>
  );
}
