import { List, ListB } from "@/types";

export const ProvincesList: List = [
  { id: 1, name: "Buenos Aires" },
  { id: 2, name: "Catamarca" },
  { id: 3, name: "Chaco" },
  { id: 4, name: "Chubut" },
  { id: 5, name: "Córdoba" },
  { id: 6, name: "Corrientes" },
  { id: 7, name: "Entre Ríos" },
  { id: 8, name: "Formosa" },
  { id: 9, name: "Jujuy" },
  { id: 10, name: "La Pampa" },
  { id: 11, name: "La Rioja" },
  { id: 12, name: "Mendoza" },
  { id: 13, name: "Misiones" },
  { id: 14, name: "Neuquén" },
  { id: 15, name: "Río Negro" },
  { id: 16, name: "Salta" },
  { id: 17, name: "San Juan" },
  { id: 18, name: "San Luis" },
  { id: 19, name: "Santa Cruz" },
  { id: 20, name: "Santa Fe" },
  { id: 21, name: "Santiago del Estero" },
  { id: 22, name: "Tierra del Fuego, Antártida e Islas del Atlántico Sur" },
  { id: 23, name: "Tucumán" },
];

// TODO: Areas for each province
export const BsAsAreasLists: List = [
  { id: 1, name: 'Adolfo Alsina' },
  { id: 51, name: 'Adolfo Gonzales Chaves' },
  { id: 2, name: 'Alberti' },
  { id: 3, name: 'Almirante Brown' },
  { id: 10, name: 'Arrecifes' },
  { id: 4, name: 'Avellaneda' },
  { id: 5, name: 'Ayacucho' },
  { id: 6, name: 'Azul' },
  { id: 7, name: 'Bahía Blanca' },
  { id: 8, name: 'Balcarce' },
  { id: 9, name: 'Baradero' },
  { id: 53, name: 'Benito Juárez' },
  { id: 120, name: 'Berazategui' },
  { id: 114, name: 'Berisso' },
  { id: 11, name: 'Bolívar' },
  { id: 12, name: 'Bragado' },
  { id: 13, name: 'Brandsen' },
  { id: 14, name: 'Campana' },
  { id: 15, name: 'Cañuelas' },
  { id: 121, name: 'Capitán Sarmiento' },
  { id: 16, name: 'Carlos Casares' },
  { id: 17, name: 'Carlos Tejedor' },
  { id: 18, name: 'Carmen de Areco' },
  { id: 20, name: 'Castelli' },
  { id: 26, name: 'Chacabuco' },
  { id: 27, name: 'Chascomús' },
  { id: 28, name: 'Chivilcoy' },
  { id: 21, name: 'Colón' },
  { id: 22, name: 'Coronel Dorrego' },
  { id: 23, name: 'Coronel Pringles' },
  { id: 113, name: 'Coronel Rosales' },
  { id: 24, name: 'Coronel Suárez' },
  { id: 19, name: 'Daireaux' },
  { id: 29, name: 'Dolores' },
  { id: 115, name: 'Ensenada' },
  { id: 118, name: 'Escobar' },
  { id: 30, name: 'Esteban Echeverría' },
  { id: 31, name: 'Exaltación de la Cruz' },
  { id: 130, name: 'Ezeiza' },
  { id: 32, name: 'Florencio Varela' },
  { id: 128, name: 'Florentino Ameghino' },
  { id: 33, name: 'General Alvarado' },
  { id: 34, name: 'General Alvear' },
  { id: 35, name: 'General Arenales' },
  { id: 36, name: 'General Belgrano' },
  { id: 37, name: 'General Guido' },
  { id: 40, name: 'General La Madrid' },
  { id: 41, name: 'General Las Heras' },
  { id: 42, name: 'General Lavalle' },
  { id: 39, name: 'General Madariaga' },
  { id: 43, name: 'General Paz' },
  { id: 44, name: 'General Pinto' },
  { id: 45, name: 'General Pueyrredón' },
  { id: 46, name: 'General Rodríguez' },
  { id: 47, name: 'General San Martín' },
  { id: 49, name: 'General Viamonte' },
  { id: 50, name: 'General Villegas' },
  { id: 52, name: 'Guaminí' },
  { id: 119, name: 'Hipólito Yrigoyen' },
  { id: 135, name: 'Hurlingham' },
  { id: 123, name: 'Islas Baradero' },
  { id: 314, name: 'Islas Campana' },
  { id: 398, name: 'Islas de San Nicolas' },
  { id: 338, name: 'Islas de Zárate' },
  { id: 387, name: 'Islas Ramallo' },
  { id: 396, name: 'Islas San Fernando' },
  { id: 399, name: 'Islas San Pedro' },
  { id: 357, name: 'Islas Tigre' },
  { id: 136, name: 'Ituzaingó' },
  { id: 132, name: 'José C. Paz' },
  { id: 54, name: 'Junín' },
  { id: 123, name: 'La Costa' },
  { id: 70, name: 'La Matanza' },
  { id: 55, name: 'La Plata' },
  { id: 25, name: 'Lanús' },
  { id: 56, name: 'Laprida' },
  { id: 58, name: 'Las Flores' },
  { id: 59, name: 'Leandro N. Alem' },
  { id: 137, name: 'Lezama' },
  { id: 60, name: 'Lincoln' },
  { id: 61, name: 'Lobería' },
  { id: 62, name: 'Lobos' },
  { id: 63, name: 'Lomas de Zamora' },
  { id: 64, name: 'Luján' },
  { id: 65, name: 'Magdalena' },
  { id: 66, name: 'Maipú' },
  { id: 133, name: 'Malvinas Argentinas' },
  { id: 69, name: 'Mar Chiquita' },
  { id: 68, name: 'Marcos Paz' },
  { id: 71, name: 'Mercedes' },
  { id: 72, name: 'Merlo' },
  { id: 73, name: 'Monte' },
  { id: 126, name: 'Monte Hermoso' },
  { id: 74, name: 'Moreno' },
  { id: 101, name: 'Morón' },
  { id: 75, name: 'Navarro' },
  { id: 76, name: 'Necochea' },
  { id: 77, name: 'Nueve de Julio' },
  { id: 78, name: 'Olavarría' },
  { id: 79, name: 'Patagones' },
  { id: 80, name: 'Pehuajó' },
  { id: 81, name: 'Pellegrini' },
  { id: 82, name: 'Pergamino' },
  { id: 83, name: 'Pila' },
  { id: 84, name: 'Pilar' },
  { id: 124, name: 'Pinamar' },
  { id: 129, name: 'Presidente Perón' },
  { id: 85, name: 'Puan' },
  { id: 134, name: 'Punta Indio' },
  { id: 86, name: 'Quilmes' },
  { id: 87, name: 'Ramallo' },
  { id: 88, name: 'Rauch' },
  { id: 89, name: 'Rivadavia' },
  { id: 90, name: 'Rojas' },
  { id: 91, name: 'Roque Pérez' },
  { id: 92, name: 'Saavedra' },
  { id: 93, name: 'Saladillo' },
  { id: 122, name: 'Salliqueló' },
  { id: 67, name: 'Salto' },
  { id: 94, name: 'San Andrés de Giles' },
  { id: 95, name: 'San Antonio de Areco' },
  { id: 116, name: 'San Cayetano' },
  { id: 96, name: 'San Fernando' },
  { id: 97, name: 'San Isidro' },
  { id: 131, name: 'San Miguel' },
  { id: 98, name: 'San Nicolás' },
  { id: 99, name: 'San Pedro' },
  { id: 100, name: 'San Vicente' },
  { id: 102, name: 'Suipacha' },
  { id: 103, name: 'Tandil' },
  { id: 104, name: 'Tapalqué' },
  { id: 57, name: 'Tigre' },
  { id: 105, name: 'Tordillo' },
  { id: 106, name: 'Tornquist' },
  { id: 107, name: 'Trenque Lauquen' },
  { id: 108, name: 'Tres Arroyos' },
  { id: 117, name: 'Tres de Febrero' },
  { id: 127, name: 'Tres Lomas' },
  { id: 109, name: 'Veinticinco de Mayo' },
  { id: 110, name: 'Vicente López' },
  { id: 125, name: 'Villa Gesell' },
  { id: 111, name: 'Villarino' },
  { id: 38, name: 'Zárate' },
];

export const GenderList: List = [
  { id: 1, name: "Macho" },
  { id: 2, name: "Hembra" },
  // TODO: BORRAR -> testing
  { id: 3, name: "string" }
]

export const BreedList: ListB = [
  { label: "Labrador", value: "1" },
  { label: "Ovejero Alemán", value: "2" },
  { label: "Sin raza", value: "3" },
]                                 
